Use venv instead of virtualenv and latest dev tools in requirements.txt
Was getting error with older versions:
  ImportError: cannot import name 'environmentfilter' from 'jinja2'